apiVersion: v1
kind: Secret
metadata:
  name: docker-hub-secret # nome do Secret
type: kubernetes.io/dockerconfigjson # tipo do Secret, neste caso é um Secret que armazena credenciais Docker
data:
  .dockerconfigjson: |
    ewogICAgICAgICJhdXRocyI6IHsKICAgICAgICAgICAgICAgICJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CiAgICAgICAgICAgICAgICAgICAgICAgICJhdXRoIjogIlpHRnVhV3h2WkdWMmIzQnpPbVJqYTNKZmNHRjBYMlZ1V2xZNVVXRjRTRGx1VDJGcGJIQkZWV3hRT1dnekxWazBZdz09IgogICAgICAgICAgICAgICAgIH0KICAgICAgICB9Cn0=
