apiVersion: v1
kind: Pod
metadata:
  labels:
    run: task-day2
  name: task-day2
spec:
  containers:
  - image: nginx
    name: webserver
    volumeMounts:
    - mountPath: /giropops
      name: primeiro-emptydir
  - image: alpine
    name: alpine
    volumeMounts:
    - mountPath: /volume
      name: primeiro-emptydir
    args:
      - sleep
      - "1600"    
    resources:
      limits:
        cpu: "1"
        memory: "128Mi"   
      requests:
        cpu: "0.5"
        memory: "64Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: primeiro-emptydir
    emptyDir:
      sizeLimit: 256Mi
